export const ADD_PRODUCT_BASKET= 'ADD_PRODUCT_BASKET';
export const GET_NUMBER_BASKET= 'GET_NUMBER_BASKET';
export const INCREASE_QUANTITY= 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY= 'DECREASE_QUANTITY';
export const CLEAR_PRODUCT= 'CLEAR_PRODUCT';
export const FETCH_PROUDCT='FETCH_PROUDCT';
export const FETCH_PROUDCT_FAIL='FETCH_PROUDCT_FAIL';
export const PRODUCT_LIST_REQUEST="PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS="PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL="PRODUCT_LIST_FAIL";
export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL ="PRODUCT_DETAILS_FAIL";
export const PRODUCT_TOP_REQUEST="PRODUCT_TOP_REQUEST";
export const PRODUCT_TOP_SUCCESS="PRODUCT_TOP_SUCCESS";
export const PRODUCT_TOP_FAIL='PRODUCT_TOP_FAIL';





